# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-22 01:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bsdemp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Album',
            new_name='Employee',
        ),
    ]
