# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-22 17:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bsdemp', '0002_auto_20160721_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='photo',
            field=models.CharField(default=2, max_length=200),
            preserve_default=False,
        ),
    ]
